object Versions {
    const val accompanistVersion = "0.28.0"
    const val activityComposeVersion = "1.5.1"
    const val androidDesugaringVersion = "1.1.5"
    const val appcompatVersion = "1.5.1"
    const val coilVersion = "2.2.1"
    const val composeVersion = "1.3.1"
    const val kotlinCompilerVersion = "1.3.2"
    const val constraintLayoutComposeVersion = "1.0.1"
    const val coreVersion = "1.9.0"
    const val junitVersion = "4.13.2"
    const val koinVersion = "3.2.0"
    const val lifecycleVersion = "2.5.1"
    const val materialVersion = "1.6.1"
    const val retrofitVersion = "2.9.0"
    const val loggingInterceptorVersion = "4.10.0"
    const val testExtVersion = "1.1.3"
    const val testEspressoCoreVersion = "3.4.0"

    const val gradlePluginVersion = "7.3.1"
    const val kotlinPluginVersion = "1.7.20"
}
